### PR TITLE
Added support for regular Apex 7 Keyboard

### PR DESCRIPTION
**Pull request by abodelot**
Hi @FrankGrimm, I've recently acquired a regular Steelseries Apex 7 keyboard, and I was very pleased to find this repository!

Please find support for the regular version:
- The `Device` class will match on the first Apex 7 keyboard found (regular or tkl). I think this is the more convenient approach, so the user doesn't have to bother configuring the model name somewhere.
- Added the keypad keycodes, and the `KEYPAD` region
- Updated udev rule
- Updated doc

### CODE REVIEW

**Comment by FrankGrimm** [comment]
Looks great, thanks @abodelot!

I've merged the changes, though I've changed the lookup to iterate over the known targets instead of all USB devices and reintroduced the exception handler in there. Does that work for you? #https://github.com/FrankGrimm/apex7tkl_linux/commit/ed9b3eaa341294a5c7da1a9eea6ac00fdb81c23d

**Comment by abodelot** [comment]
Thanks a lot!

>  I've changed the lookup to iterate over the known targets instead of all USB devices and reintroduced the exception handler in there. 

That's much more efficient :+1:

**Comment by abodelot** [comment]
On a second thought, 

```py
 for target in TARGETS:
        try:
            dev = usb.core.find(idVendor = target['idVendor'], idProduct = target['idProduct'])
            if dev is not None:
                return target, dev
        except USBError as e:
            print(f"usb::find({target['name']}) failed: {e}")
```

It means TKL users will attempt to find the Regular version first, and they'll get the exception printed to stdout, which can be quite misleading IMO.

What do you think it's best?

**Comment by FrankGrimm** [comment]
That `.find` call shouldn't throw an error, it just returns `None` if the target isn't present.

At least that's the [documented](https://www.kite.com/python/docs/usb.core.find) behaviour and works as expected on the two machines I tested on.

**Comment by abodelot** [comment]
Oh, nice, you're right. Nevermind then :+1:

**Pull request merged**
